package com.jee.learn.dto;

import java.io.Serializable;
import java.util.List;

/**
 * jstree对象
 * 
 * <pre>
 * Expected format of the node (there are no required fields)
 * {
 *   id          : "string" // will be autogenerated if omitted
 *   text        : "string" // node text
 *   icon        : "string" // string for custom
 *   state       : {
 *     opened    : boolean  // is the node open
 *     disabled  : boolean  // is the node disabled
 *     selected  : boolean  // is the node selected
 *   },
 *   children    : []  // array of strings or objects
 *   li_attr     : {}  // attributes for the generated LI node
 *   a_attr      : {}  // attributes for the generated A node
 * }
 * </pre>
 * 
 * @author 9003286
 */
public class JsTree implements Serializable {

    private static final long serialVersionUID = -7955458236429058717L;

    private String id;

    private String text;

    private String icon;

    private JsTreeState state;

    public List<JsTree> children;

    public Object li_attr;

    public Object a_attr;

    private String parent;// 顶级 "#" 或 父级id

    public JsTree() {
    }

    public JsTree(String id, String text, String icon, boolean isOpen) {
        this.id = id;
        this.text = text;
        this.icon = icon;
        this.state = new JsTreeState(isOpen);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public JsTreeState getState() {
        return state;
    }

    public void setState(JsTreeState state) {
        this.state = state;
    }

    public List<JsTree> getChildren() {
        return children;
    }

    public void setChildren(List<JsTree> children) {
        this.children = children;
    }

    public Object getLi_attr() {
        return li_attr;
    }

    public void setLi_attr(Object li_attr) {
        this.li_attr = li_attr;
    }

    public Object getA_attr() {
        return a_attr;
    }

    public void setA_attr(Object a_attr) {
        this.a_attr = a_attr;
    }

    public String getParent() {
        return parent;
    }

    public void setParent(String parent) {
        this.parent = parent;
    }

}
